# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('descriptor', models.URLField()),
                ('state', models.CharField(choices=[('i', 'Invisible to Students'), ('c', 'Closed for Submissions'), ('s', 'Accepting Solutions Only'), ('a', 'Accepting Solutions and Tests'), ('t', 'Accepting Tests Only')], default='i', max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Course')),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Course')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FileField(max_length=256, upload_to=student.models.solution_directory_path)),
                ('coursework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Coursework')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_solution', 'Can view this solution'),),
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FileField(max_length=256, upload_to=student.models.test_directory_path)),
                ('has_run', models.BooleanField()),
                ('results', models.FileField(max_length=256, null=True, upload_to=student.models.results_directory_path)),
                ('feedback', models.FileField(max_length=256, null=True, upload_to=student.models.feedback_directory_path)),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.TestCase'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolleduser',
            unique_together=set([('login', 'course')]),
        ),
    ]
