# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('descriptor', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FileField(max_length=256, upload_to=student.models.solution_directory_path)),
                ('coursework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Coursework')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FileField(max_length=256, upload_to=student.models.test_directory_path)),
                ('has_run', models.BooleanField()),
                ('results', models.FileField(max_length=256, null=True, upload_to=student.models.results_directory_path)),
                ('feedback', models.FileField(max_length=256, null=True, upload_to=student.models.feedback_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('login', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('type', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.UserType'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.User'),
        ),
        migrations.AddField(
            model_name='solution',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.User'),
        ),
        migrations.AddField(
            model_name='solution',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.TestCase'),
        ),
        migrations.AddField(
            model_name='enrolleduser',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.User'),
        ),
        migrations.AddField(
            model_name='enrolleduser',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Module'),
        ),
        migrations.AddField(
            model_name='coursework',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Module'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolleduser',
            unique_together=set([('login', 'module')]),
        ),
    ]
