# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedsolution',
            name='file',
            field=models.FileField(upload_to='solutions'),
        ),
    ]
