# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20161215_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedsolution',
            name='cwid',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='storedsolution',
            name='userid',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='storedsolution',
            name='file',
            field=models.FileField(upload_to=student.models.user_directory_path),
        ),
    ]
