# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 10:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForTestMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.FeedbackGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Coursework')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.FeedbackGroup')),
            ],
        ),
        migrations.AddField(
            model_name='feedbackfortestmatch',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.FeedbackGroup'),
        ),
        migrations.AddField(
            model_name='feedbackfortestmatch',
            name='test_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.TestMatch'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackplan',
            unique_together=set([('group', 'coursework')]),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackmembership',
            unique_together=set([('group', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackfortestmatch',
            unique_together=set([('group', 'test_match')]),
        ),
    ]
